name: ship_hours
description: Commercial work hours tracker for seafarers.
publish_to: "none"

version: 0.2.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  provider: ^6.1.2
  path_provider: ^2.1.4
  pdf: ^3.11.1
  share_plus: ^10.1.4
  file_selector: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
