import 'dart:io';

import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../../core/enums/currency_type.dart';
import '../../domain/entities/app_settings.dart';
import '../../domain/entities/month_statistics.dart';
import '../../domain/entities/salary_calculation.dart';

final class ReportExportService {
  const ReportExportService._();

  static const MethodChannel _fileExportChannel = MethodChannel(
    'com.example.ship_hours/file_export',
  );

  static Future<void> exportPdf({
    required MonthStatistics statistics,
    required AppSettings settings,
    required DateTime month,
    required SalaryCalculation? salaryCalculation,
    required bool share,
  }) async {
    final document = pw.Document();
    final period = DateFormat.yMMMM().format(month);

    final salary = salaryCalculation;

    final basicPay = salary == null
        ? statistics.regularPay
        : salary.basicUk +
            salary.basicNonUk +
            salary.leaveUk +
            salary.leaveNonUk;

    final overtimePay = salary == null
        ? statistics.overtimePay
        : salary.guaranteedOtUk +
            salary.guaranteedOtNonUk +
            salary.extraOtUk +
            salary.extraOtNonUk;

    final additionalPay =
        salary == null ? 0.0 : salary.lashingBonus + salary.travelAllowance;

    final deductions = salary?.canteenDeduction ?? 0.0;
    final totalPay = salary?.total ?? statistics.totalPay;

    document.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.stretch,
            children: [
              pw.Text(
                'Ship Hours Report',
                style: const pw.TextStyle(
                  fontSize: 26,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 6),
              pw.Text(
                period,
                style: const pw.TextStyle(
                  fontSize: 14,
                  color: PdfColors.grey700,
                ),
              ),
              pw.SizedBox(height: 24),
              _sectionTitle('Hours'),
              _row('Total hours', _hours(statistics.totalHours)),
              _row('Regular hours', _hours(statistics.regularHours)),
              _row('Overtime total', _hours(statistics.overtimeHours)),
              _row(
                'Fixed OT',
                '-${_hours(statistics.fixedOvertimeHours)}',
              ),
              _row(
                'Paid OT',
                _hours(statistics.paidOvertimeHours),
              ),
              _row(
                'Holiday hours',
                _hours(statistics.holidayHours),
              ),
              pw.SizedBox(height: 18),
              _sectionTitle('Salary'),
              _row(
                'Basic pay',
                _money(basicPay, settings.currency),
              ),
              _row(
                'Overtime pay',
                _money(overtimePay, settings.currency),
              ),
              _row(
                'Allowances',
                _money(additionalPay, settings.currency),
              ),
              _row(
                'Deductions',
                '-${_money(deductions, settings.currency)}',
              ),
              pw.Divider(height: 28),
              _totalRow(
                'Total',
                _money(totalPay, settings.currency),
              ),
              pw.Spacer(),
              pw.Text(
                'Generated by Ship Hours',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                ),
              ),
              pw.Text(
                'Created by LEVCHIK',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          );
        },
      ),
    );

    final file = await _writeBytes(
      fileName: 'ShipHours_Report_${DateFormat('yyyy-MM').format(month)}.pdf',
      bytes: await document.save(),
    );
    if (share) {
      await Share.shareXFiles(
        [XFile(file.path)],
        text: 'Ship Hours PDF report',
      );
    } else {
      await _saveWithDialog(
        sourceFile: file,
        mimeType: 'application/pdf',
        extensions: const ['pdf'],
      );
    }
  }

  static Future<void> exportCsv({
    required MonthStatistics statistics,
    required AppSettings settings,
    required DateTime month,
    required SalaryCalculation? salaryCalculation,
    required bool share,
  }) async {
    final salary = salaryCalculation;

    final basicPay = salary == null
        ? statistics.regularPay
        : salary.basicUk +
            salary.basicNonUk +
            salary.leaveUk +
            salary.leaveNonUk;

    final overtimePay = salary == null
        ? statistics.overtimePay
        : salary.guaranteedOtUk +
            salary.guaranteedOtNonUk +
            salary.extraOtUk +
            salary.extraOtNonUk;

    final additionalPay =
        salary == null ? 0.0 : salary.lashingBonus + salary.travelAllowance;

    final deductions = salary?.canteenDeduction ?? 0.0;
    final totalPay = salary?.total ?? statistics.totalPay;

    final rows = <List<String>>[
      [
        'Ship Hours Report',
        DateFormat.yMMMM().format(month),
      ],
      ['Metric', 'Value'],
      [
        'Total hours',
        statistics.totalHours.toStringAsFixed(1),
      ],
      [
        'Regular hours',
        statistics.regularHours.toStringAsFixed(1),
      ],
      [
        'Overtime total',
        statistics.overtimeHours.toStringAsFixed(1),
      ],
      [
        'Fixed OT',
        statistics.fixedOvertimeHours.toStringAsFixed(1),
      ],
      [
        'Paid OT',
        statistics.paidOvertimeHours.toStringAsFixed(1),
      ],
      [
        'Holiday hours',
        statistics.holidayHours.toStringAsFixed(1),
      ],
      ['Basic pay', basicPay.toStringAsFixed(2)],
      ['Overtime pay', overtimePay.toStringAsFixed(2)],
      ['Allowances', additionalPay.toStringAsFixed(2)],
      ['Deductions', deductions.toStringAsFixed(2)],
      ['Total pay', totalPay.toStringAsFixed(2)],
      ['Currency', settings.currency.code.toUpperCase()],
      ['Created by', 'LEVCHIK'],
    ];

    final csv = rows.map((row) => row.map(_csvCell).join(',')).join('\n');

    final file = await _writeString(
      fileName: 'ShipHours_Report_${DateFormat('yyyy-MM').format(month)}.csv',
      contents: csv,
    );
    if (share) {
      await Share.shareXFiles(
        [XFile(file.path)],
        text: 'Ship Hours CSV report',
      );
    } else {
      await _saveWithDialog(
        sourceFile: file,
        mimeType: 'text/csv',
        extensions: const ['csv'],
      );
    }
  }

  static Future<File> _writeBytes({
    required String fileName,
    required List<int> bytes,
  }) async {
    final directory = await getTemporaryDirectory();
    final shareFile = File('${directory.path}/$fileName');

    await shareFile.writeAsBytes(
      bytes,
      flush: true,
    );

    return shareFile;
  }

  static Future<File> _writeString({
    required String fileName,
    required String contents,
  }) async {
    final directory = await getTemporaryDirectory();
    final shareFile = File('${directory.path}/$fileName');

    await shareFile.writeAsString(
      contents,
      flush: true,
    );

    return shareFile;
  }

  static Future<void> _saveWithDialog({
    required File sourceFile,
    required String mimeType,
    required List<String> extensions,
  }) async {
    final fileName = sourceFile.uri.pathSegments.last;

    final saved = await _fileExportChannel.invokeMethod<bool>(
      'saveFile',
      {
        'sourcePath': sourceFile.path,
        'suggestedName': fileName,
        'mimeType': mimeType,
      },
    );

    // false означает, что пользователь закрыл системное окно.
    // Это нормальная отмена, а не ошибка экспорта.
    if (saved == false) {
      return;
    }

    if (saved != true) {
      throw const FileSystemException(
        'Android did not confirm that the report was saved.',
      );
    }
  }

  static String _money(
    double amount,
    CurrencyType currency,
  ) {
    final currencyCode = currency.code.toUpperCase();
    return '$currencyCode ${amount.toStringAsFixed(2)}';
  }

  static String _hours(double value) {
    return '${value.toStringAsFixed(1)} h';
  }

  static String _csvCell(String value) {
    final escaped = value.replaceAll('"', '""');
    return '"$escaped"';
  }

  static pw.Widget _sectionTitle(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Text(
        text,
        style: const pw.TextStyle(
          fontSize: 16,
          fontWeight: pw.FontWeight.bold,
        ),
      ),
    );
  }

  static pw.Widget _row(
    String label,
    String value,
  ) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        children: [
          pw.Expanded(
            child: pw.Text(label),
          ),
          pw.Text(
            value,
            style: const pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _totalRow(
    String label,
    String value,
  ) {
    return pw.Row(
      children: [
        pw.Expanded(
          child: pw.Text(
            label,
            style: const pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),
        pw.Text(
          value,
          style: const pw.TextStyle(
            fontSize: 22,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      ],
    );
  }
}
