import 'dart:io';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../../core/utils/money_formatter.dart';
import '../../domain/entities/app_settings.dart';
import '../../core/enums/currency_type.dart';
import '../../core/enums/currency_type.dart';
import '../../domain/entities/month_statistics.dart';

final class ReportExportService {
  const ReportExportService._();

  static Future<void> exportPdf({
    required MonthStatistics statistics,
    required AppSettings settings,
    required DateTime month,
  }) async {
    final document = pw.Document();
    final period = DateFormat.yMMMM().format(month);

    document.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.stretch,
            children: [
              pw.Text('Ship Hours Report', style: pw.TextStyle(fontSize: 26, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 6),
              pw.Text(period, style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
              pw.SizedBox(height: 24),
              _sectionTitle('Hours'),
              _row('Total hours', _hours(statistics.totalHours)),
              _row('Regular hours', _hours(statistics.regularHours)),
              _row('Overtime total', _hours(statistics.overtimeHours)),
              _row('Fixed OT', '-${_hours(statistics.fixedOvertimeHours)}'),
              _row('Paid OT', _hours(statistics.paidOvertimeHours)),
              _row('Holiday hours', _hours(statistics.holidayHours)),
              pw.SizedBox(height: 18),
              _sectionTitle('Salary'),
              _row('Base salary', _money(statistics.baseSalary, settings.currency)),
              _row('Regular pay', _money(statistics.regularPay, settings.currency)),
              _row('Overtime pay', _money(statistics.overtimePay, settings.currency)),
              _row('Holiday pay', _money(statistics.holidayPay, settings.currency)),
              pw.Divider(height: 28),
              _totalRow('Total', _money(statistics.totalPay, settings.currency)),
              pw.Spacer(),
              pw.Text('Generated by Ship Hours', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
              pw.Text('Created by LEVCHIK', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
            ],
          );
        },
      ),
    );

    final file = await _writeBytes(
      fileName: 'ship_hours_${DateFormat('yyyy_MM').format(month)}.pdf',
      bytes: await document.save(),
    );
    await Share.shareXFiles([XFile(file.path)], text: 'Ship Hours PDF report');
  }

  static Future<void> exportCsv({
    required MonthStatistics statistics,
    required AppSettings settings,
    required DateTime month,
  }) async {
    final rows = <List<String>>[
      ['Ship Hours Report', DateFormat.yMMMM().format(month)],
      ['Metric', 'Value'],
      ['Total hours', statistics.totalHours.toStringAsFixed(1)],
      ['Regular hours', statistics.regularHours.toStringAsFixed(1)],
      ['Overtime total', statistics.overtimeHours.toStringAsFixed(1)],
      ['Fixed OT', statistics.fixedOvertimeHours.toStringAsFixed(1)],
      ['Paid OT', statistics.paidOvertimeHours.toStringAsFixed(1)],
      ['Holiday hours', statistics.holidayHours.toStringAsFixed(1)],
      ['Base salary', statistics.baseSalary.toStringAsFixed(2)],
      ['Regular pay', statistics.regularPay.toStringAsFixed(2)],
      ['Overtime pay', statistics.overtimePay.toStringAsFixed(2)],
      ['Holiday pay', statistics.holidayPay.toStringAsFixed(2)],
      ['Total pay', statistics.totalPay.toStringAsFixed(2)],
      ['Currency', settings.currency.code],
      ['Created by', 'LEVCHIK'],
    ];

    final csv = rows.map((row) => row.map(_csvCell).join(',')).join('\n');
    final file = await _writeString(
      fileName: 'ship_hours_${DateFormat('yyyy_MM').format(month)}.csv',
      contents: csv,
    );
    await Share.shareXFiles([XFile(file.path)], text: 'Ship Hours CSV report');
  }

  static Future<File> _writeBytes({required String fileName, required List<int> bytes}) async {
    final directory = await getTemporaryDirectory();
    final file = File('${directory.path}/$fileName');
    return file.writeAsBytes(bytes, flush: true);
  }

  static Future<File> _writeString({required String fileName, required String contents}) async {
    final directory = await getTemporaryDirectory();
    final file = File('${directory.path}/$fileName');
    return file.writeAsString(contents, flush: true);
  }

  static String _money(double amount, CurrencyType currency) => MoneyFormatter.format(amount: amount, currency: currency);

  static String _hours(double value) => '${value.toStringAsFixed(1)} h';

  static String _csvCell(String value) {
    final escaped = value.replaceAll('"', '""');
    return '"$escaped"';
  }

  static pw.Widget _sectionTitle(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Text(text, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
    );
  }

  static pw.Widget _row(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        children: [
          pw.Expanded(child: pw.Text(label)),
          pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  static pw.Widget _totalRow(String label, String value) {
    return pw.Row(
      children: [
        pw.Expanded(child: pw.Text(label, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold))),
        pw.Text(value, style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
      ],
    );
  }
}
